import { getAllSubjects, getLegacyIdForSubjectCode } from '@/subjects';

export const apSubjects = [
  {
    id: "macroeconomics",
    name: "AP Macroeconomics",
    description: "Economic indicators, national income, fiscal policy, monetary policy, and international trade",
    units: 6,
    difficulty: "Medium",
    examDate: "May 8, 2026",
    isActive: true,
  },
  {
    id: "microeconomics",
    name: "AP Microeconomics",
    description: "Supply and demand, market structures, factor markets, and market failures",
    units: 6,
    difficulty: "Medium",
    examDate: "May 4, 2026",
    isActive: true,
  },
  {
    id: "computer-science-principles",
    name: "AP Computer Science Principles",
    description: "Computational thinking, programming, internet, data analysis, and impact of computing",
    units: 5,
    difficulty: "Easy",
    examDate: "May 14, 2026",
    isActive: true,
  },
  {
    id: "chemistry",
    name: "AP Chemistry",
    description: "Atomic structure, bonding, reactions, kinetics, thermodynamics, and equilibrium",
    units: 9,
    difficulty: "Hard",
    examDate: "May 5, 2026",
    isActive: true,
  },
  {
    id: "government",
    name: "AP U.S. Government and Politics",
    description: "Constitutional foundations, branches of government, civil liberties and rights, political ideologies, and participation",
    units: 5,
    difficulty: "Medium",
    examDate: "May 5, 2026",
    isActive: true,
  },
  {
    id: "psychology",
    name: "AP Psychology",
    description: "Biological bases, cognition, development, social psychology, and mental and physical health",
    units: 5,
    difficulty: "Medium",
    examDate: "May 12, 2026",
    isActive: true,
  },
  {
    id: "biology",
    name: "AP Biology",
    description: "Cell biology, genetics, evolution, ecology, and biological systems",
    units: 8,
    difficulty: "Hard",
    examDate: "May 4, 2026",
    isActive: true,
  },
  {
    id: "calculus-ab",
    name: "AP Calculus AB",
    description: "Limits, derivatives, integrals, and the Fundamental Theorem of Calculus",
    units: 8,
    difficulty: "Hard",
    examDate: "May 11, 2026",
    isActive: true,
  },
  {
    id: "calculus-bc",
    name: "AP Calculus BC",
    description: "All Calculus AB topics plus parametric, polar, vector functions, and infinite series",
    units: 10,
    difficulty: "Very Hard",
    examDate: "May 11, 2026",
    isActive: true,
  },
  {
    id: "computer-science-a",
    name: "AP Computer Science A",
    description: "Object-oriented programming in Java, data structures, algorithms, and recursion",
    units: 10,
    difficulty: "Hard",
    examDate: "May 15, 2026",
    isActive: true,
  },
  {
    id: "us-history",
    name: "AP U.S. History",
    description: "American history from pre-Columbian societies to the present day",
    units: 9,
    difficulty: "Hard",
    examDate: "May 8, 2026",
    isActive: true,
  },
  {
    id: "world-history",
    name: "AP World History: Modern",
    description: "Global history from 1200 CE to the present with emphasis on cross-cultural interactions",
    units: 9,
    difficulty: "Hard",
    examDate: "May 7, 2026",
    isActive: true,
  },
  {
    id: "european-history",
    name: "AP European History",
    description: "European history from 1450 to the present including political, economic, and cultural developments",
    units: 9,
    difficulty: "Hard",
    examDate: "May 4, 2026",
    isActive: true,
  },
  {
    id: "english-language",
    name: "AP English Language and Composition",
    description: "Rhetorical analysis, argumentation, synthesis, and nonfiction writing",
    units: 5,
    difficulty: "Medium",
    examDate: "May 13, 2026",
    isActive: true,
  },
  {
    id: "english-literature",
    name: "AP English Literature and Composition",
    description: "Literary analysis of fiction, poetry, and drama from various periods and genres",
    units: 9,
    difficulty: "Hard",
    examDate: "May 6, 2026",
    isActive: true,
  },
  {
    id: "statistics",
    name: "AP Statistics",
    description: "Data analysis, probability, statistical inference, and experimental design",
    units: 9,
    difficulty: "Hard",
    examDate: "May 7, 2026",
    isActive: true,
  },
  {
    id: "physics-1",
    name: "AP Physics 1: Algebra-Based",
    description: "Kinematics, dynamics, energy, momentum, rotational motion, and simple harmonic motion",
    units: 7,
    difficulty: "Very Hard",
    examDate: "May 6, 2026",
    isActive: true,
  },
  {
    id: "physics-2",
    name: "AP Physics 2: Algebra-Based",
    description: "Fluids, thermodynamics, electricity, magnetism, optics, and modern physics",
    units: 7,
    difficulty: "Very Hard",
    examDate: "May 7, 2026",
    isActive: true,
  },
  {
    id: "environmental-science",
    name: "AP Environmental Science",
    description: "Ecosystems, biodiversity, pollution, energy resources, and global change",
    units: 9,
    difficulty: "Medium",
    examDate: "May 15, 2026",
    isActive: true,
  },
  {
    id: "human-geography",
    name: "AP Human Geography",
    description: "Population, cultural patterns, political organization, agriculture, urbanization, and development",
    units: 7,
    difficulty: "Easy",
    examDate: "May 5, 2026",
    isActive: true,
  },
];

export const difficultyColors: Record<string, string> = {
  "Easy": "bg-green-100 text-green-800 border-green-200",
  "Medium": "bg-yellow-100 text-yellow-800 border-yellow-200",
  "Hard": "bg-orange-100 text-orange-800 border-orange-200",
  "Very Hard": "bg-red-100 text-red-800 border-red-200"
};
