
export function getKeywords() {
  return {
    FAD: [
      'constitution',
      'federalism',
      'separation of powers',
      'checks and balances',
      'democracy',
      'republic',
      'limited government',
      'popular sovereignty',
      'social contract',
      'enlightenment',
    ],
    IAB: [
      'congress',
      'presidency',
      'bureaucracy',
      'federal courts',
      'supreme court',
      'judicial review',
      'executive orders',
      'legislation',
      'veto',
      'oversight',
    ],
    CLCR: [
      'civil liberties',
      'civil rights',
      'first amendment',
      'due process',
      'equal protection',
      'selective incorporation',
      'bill of rights',
      'fourteenth amendment',
      'discrimination',
      'affirmative action',
    ],
    APIB: [
      'political ideology',
      'political socialization',
      'public opinion',
      'polling',
      'political culture',
      'liberal',
      'conservative',
      'libertarian',
      'generational effects',
      'lifecycle effects',
    ],
    PP: [
      'voting',
      'elections',
      'political parties',
      'interest groups',
      'campaigns',
      'media',
      'linkage institutions',
      'voter turnout',
      'electoral college',
      'PACs',
    ],
  };
}
